package com.lts.movie.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lts.movie.db.Genres;

import com.lts.movie.db.GenresDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig genresDaoConfig;

    private final GenresDao genresDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        genresDaoConfig = daoConfigMap.get(GenresDao.class).clone();
        genresDaoConfig.initIdentityScope(type);

        genresDao = new GenresDao(genresDaoConfig, this);

        registerDao(Genres.class, genresDao);
    }
    
    public void clear() {
        genresDaoConfig.clearIdentityScope();
    }

    public GenresDao getGenresDao() {
        return genresDao;
    }

}
